### ISSUE TITLE
Please support .mll and .mly files

### ISSUE THREAD

**Issue by edwintorok** [def-lkb/ocp-indent-vim#7]
ocp-indent indents them wrongly, please disable ocp-indent on these files.
I have to always `set indentexpr=` to be able to edit these files otherwise it indents every other line:
```
%token <char> CHAR
              %token ANY
              %token EOF
              %token <string> STRING
                              %token BRACKET_OPEN
```

**Comment by def-lkb** [comment]
I disabled *.mll *.mly in master (vim falls back to other indentation modes, so it's not exactly like setting `indentexpr=`).

**Comment by edwintorok** [comment]
Thanks!
